"""
File: src/pipeline/feature_engineering.py

Purpose:
  Implements Step 4: Feature Engineering.  This step aggregates
  transaction‑level data into customer‑level features that will later be
  used by the segmentation algorithm.  The features include total
  quantity purchased, total revenue, average unit price, number of
  transactions and number of distinct products purchased.  The
  customer identifier is a pseudonymised hash inherited from the Gold
  layer.

Why it exists:
  Proper feature engineering transforms raw transactional data into
  meaningful signals that allow downstream algorithms to discern
  patterns across customers.

Inputs:
  - `gold_fact_sales.csv` from the Gold layer located at
    `artifacts/runs/<run_id>/gold/data`.

Outputs:
  - `customer_features.csv` written to
    `artifacts/runs/<run_id>/step2_feature_engineering/data`.
  - A feature dictionary `feature_dictionary.md` describing each
    engineered feature written to
    `artifacts/runs/<run_id>/step2_feature_engineering/reports`.

Step:
  This module belongs to the feature engineering step and must be
  executed after the Gold layer and EDA.
"""

import csv
from pathlib import Path
from typing import Dict, List


# NOTE: Execute the feature engineering step for a given run ID
def run_feature_engineering(run_id: str) -> None:
    """
    Entry point for the Feature Engineering step.

    Args:
        run_id (str): Unique identifier for this pipeline run.
    """
    # NOTE: Locate inputs and outputs
    project_root = Path(__file__).resolve().parents[2]
    gold_data = project_root / "artifacts" / "runs" / run_id / "gold" / "data"
    fe_dir = project_root / "artifacts" / "runs" / run_id / "step2_feature_engineering"
    fe_data_dir = fe_dir / "data"
    fe_reports_dir = fe_dir / "reports"
    fe_data_dir.mkdir(parents=True, exist_ok=True)
    fe_reports_dir.mkdir(parents=True, exist_ok=True)
    # Load fact table
    with open(gold_data / "gold_fact_sales.csv", newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        # Initialize accumulator per customer
        agg: Dict[str, Dict[str, float]] = {}
        prod_counts: Dict[str, set] = {}
        trans_counts: Dict[str, int] = {}
        for row in reader:
            cust = row["customer_hash"]
            qty = float(row["quantity"])
            price = float(row["unit_price"])
            revenue = qty * price
            cust_data = agg.setdefault(cust, {"total_qty": 0.0, "total_revenue": 0.0, "sum_price": 0.0})
            cust_data["total_qty"] += qty
            cust_data["total_revenue"] += revenue
            cust_data["sum_price"] += price
            prod_set = prod_counts.setdefault(cust, set())
            prod_set.add(row["product_id"])
            trans_counts[cust] = trans_counts.get(cust, 0) + 1
    # Build feature rows
    header = [
        "customer_hash",
        "total_qty",
        "total_revenue",
        "avg_unit_price",
        "num_transactions",
        "num_distinct_products",
    ]
    rows: List[List[str]] = []
    for cust, data in agg.items():
        num_trans = trans_counts[cust]
        rows.append([
            cust,
            f"{data['total_qty']}",
            f"{data['total_revenue']}",
            f"{data['sum_price'] / num_trans if num_trans > 0 else 0.0}",
            f"{num_trans}",
            f"{len(prod_counts[cust])}",
        ])
    # Write features
    with open(fe_data_dir / "customer_features.csv", "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(header)
        writer.writerows(rows)
    # Write feature dictionary
    feature_dict_lines = [
        "# Feature Dictionary",
        "",
        "| Feature | Description |",
        "|---------|-------------|",
        "| customer_hash | Pseudonymised unique customer identifier |",
        "| total_qty | Total quantity purchased across all transactions |",
        "| total_revenue | Total revenue generated by the customer |",
        "| avg_unit_price | Average unit price across transactions |",
        "| num_transactions | Number of transactions for the customer |",
        "| num_distinct_products | Number of unique products purchased |",
    ]
    (fe_reports_dir / "feature_dictionary.md").write_text("\n".join(feature_dict_lines), encoding="utf-8")
